name: parcial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15
  image_picker: ^1.0.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
