// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuAlIEb2XqYotdM3MAT-K5u7NjAf81sKA',
    appId: '1:863774638017:web:5d360f774a398660cf3940',
    messagingSenderId: '863774638017',
    projectId: 'finalprojectflutter-5c4e6',
    authDomain: 'finalprojectflutter-5c4e6.firebaseapp.com',
    storageBucket: 'finalprojectflutter-5c4e6.firebasestorage.app',
    measurementId: 'G-WJVLZ31HLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPeewJp7WxFzTi5vRJH9Cyquw6RUA06N8',
    appId: '1:863774638017:android:6e04b32e8b3cdafecf3940',
    messagingSenderId: '863774638017',
    projectId: 'finalprojectflutter-5c4e6',
    storageBucket: 'finalprojectflutter-5c4e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN4CpiqH0w10LdoXvPVcT7_jwVe4-tI74',
    appId: '1:863774638017:ios:cd32c66cb81efa39cf3940',
    messagingSenderId: '863774638017',
    projectId: 'finalprojectflutter-5c4e6',
    storageBucket: 'finalprojectflutter-5c4e6.firebasestorage.app',
    iosBundleId: 'com.example.parcial',
  );
}
